version: '3'

volumes:
    redis:

services:

### PHP-FPM Server Container ##################################
    php:
        image: dpspub/base:latest
        command: ['caddy', '-conf', '/var/default-caddyfile']
        ports:
        - "4431:443"
        links:
        - redis
        volumes:
        - .:/var/www

    ### Redis Server Container ####################################

    redis:
        image: redis:latest
        volumes:
        - redis:/var/lib/redis
